#!/usr/bin/env node

/**
 * Module dependencies.
 */

var program = require('commander');
var _ = require('./index');

program
  .version('0.0.1')
  .option('-a, --add', 'add')
  .option('-s, --subtract', 'Subtract the second number entered from the first.')
  .option('-m, --multiply', 'Multiply all numbers entered.')
  .option('-d, --divide', 'Divide the first number entered by the second.')
  .option('-p, --pert', 'Use the P * e^rt formula to calculate continually compounding interest.')
  .option('-c, --cheese [type]', 'Add the specified type of cheese [marble]', 'marble')
  .parse(process.argv);

console.log('You have entered the following instruction:');
if (program.add) {
  console.log('  : Add', program.args);
  console.log('   = ' + _.add(program.args));
}
if (program.subtract) {
  console.log('  : Subtract', program.args);
  console.log('   = ' + _.subtract(program.args));
}
if (program.multiply) {
  console.log('  : Multiply', program.args);
  console.log('   = ' + _.multifly(program.args));
}
if (program.divide) {
  console.log('  : Divide', program.args);
  console.log('   = ' + _.divide(program.args));
}
if (program.pert) {
  console.log('  : Calculate Interest of', program.args);
  console.log('   = ' + _.pert(program.args));
}
// console.log('  - %s cheese', program.cheese);

function range(val) {
  return val.split('..').map(Number);
}

function list(val) {
  return val.split(',');
}

function collect(val, memo) {
  memo.push(val);
  return memo;
}

function increaseVerbosity(v, total) {
  return total + 1;
}

program
  .version('0.0.1')
  .usage('[options] <file ...>')
  .option('-i, --integer <n>', 'An integer argument', parseInt)
  .option('-f, --float <n>', 'A float argument', parseFloat)
  .option('-r, --range <a>..<b>', 'A range', range)
  .option('-l, --list <items>', 'A list', list)
  .option('-o, --optional [value]', 'An optional value')
  .option('-c, --collect [value]', 'A repeatable value', [])
  .option('-v, --verbose', 'A value that can be increased', increaseVerbosity, 0)
  .parse(process.argv);

// console.log(' int: %j', program.integer);
// console.log(' float: %j', program.float);
// console.log(' optional: %j', program.optional);
// program.range = program.range || [];
// console.log(' range: %j..%j', program.range[0], program.range[1]);
// console.log(' list: %j', program.list);
// console.log(' collect: %j', program.collect);
// console.log(' verbosity: %j', program.verbose);
// console.log(' args: %j', program.args);

/******************************************/

// var _ = require('./index.js');

// process.argv = process.argv.slice(1);

// _.checkOperator(process.argv[2])

// console.log(_.performOp(process.argv[1], process.argv[3], process.argv[2]));


